version: "2"

checks:
  similar-code:
    enabled: true
    config:
      threshold: 75

exclude_patterns:
  - "dist/"
  - "playground/"
  - "**/node_modules/"
  - "**/tests/"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.d.ts"
