version: "2"

checks:
  return-statements:
    config:
      threshold: 8

exclude_patterns:
  - "dist/"
  - "playground/"
  - "**/node_modules/"
  - "**/tests/"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.d.ts"
