name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
        with:
          version: 7

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
        with:
          version: 7

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
        with:
          version: 7

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - run: pnpm install
      - run: pnpm test
