name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
        with:
          version: 7

      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: be11bd542160eb66e90ab4e55f54b3064ecc89375880342b4407885b6af8df39
        with:
          coverageCommand: pnpm coverage

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
        with:
          version: 7

      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint
